In [239]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import string

In [240]:
df1=pd.read_csv("/content/female.tsv", names=["Name","Gender"], sep="\t")
df2=pd.read_csv("/content/male.tsv", names=["Name","Gender"], sep="\t")

In [241]:
df1['Gender']=0 #0 là giới tính nữ
df2['Gender']=1 #1 là giới tính nam

In [242]:
df1.dtypes

Name      object
Gender     int64
dtype: object

In [243]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 2 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   Name    1000000 non-null  object
 1   Gender  1000000 non-null  int64
dtypes: int64(1), object(1)
memory usage: 15.3+ MB

In [244]:
df1

                      Name  Gender
0       Nguyễn Thị Mỹ Linh       0
1                    Vi Vi       0
2              Hang Thi Vo       0
3       Yen Phi Nguyen Thi       0
4             Trần Thị Lan       0
...                    ...     ...
999995         Phạm Yến Vi       0
999996         Lương Hường       0
999997           Sarah Sam       0
999998          Luong Hien       0
999999         Dung Nguyễn       0

[1000000 rows x 2 columns]

In [245]:
df2

                       Name  Gender
0       Nguyễn Đàm Quốc Huy       1
1              Vu Quang Tin       1
2                   Hà Thục       1
3                   Phu Pro       1
4                Relsx Nick       1
...                     ...     ...
999993          Le Chu Tieu       1
999994           Islam Khan       1
999995       သူရိန္ ကို ကို       1
999996        Ace- Mắu-lạnh       1
999997              Hang Bi       1

[999998 rows x 2 columns]

In [246]:
df=pd.concat([df1,df2])
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1999998 entries, 0 to 999997
Data columns (total 2 columns):
 #   Column  Dtype
---  ------  -----
 0   Name    object
 1   Gender  int64
dtypes: int64(1), object(1)
memory usage: 45.8+ MB

In [247]:
df

                      Name  Gender
0       Nguyễn Thị Mỹ Linh       0
1                    Vi Vi       0
2              Hang Thi Vo       0
3       Yen Phi Nguyen Thi       0
4             Trần Thị Lan       0
...                    ...     ...
999993         Le Chu Tieu       1
999994          Islam Khan       1
999995      သူရိန္ ကို ကို       1
999996       Ace- Mắu-lạnh       1
999997             Hang Bi       1

[1999998 rows x 2 columns]

In [248]:
df3 = df.sample(frac=1)

In [249]:
df3.head()

                     Name  Gender
852591             Hải Lê       1
190766  Đặng Thị Trúc Lam       0
473760        Thu Hien Le       1
62222      NgAng LÀ PhAng       1
562024           Ngọc Ánh       0

In [250]:
print(df.size)
print(df3.size)

3999996
3999996

In [251]:
from sklearn.model_selection import train_test_split 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer

In [252]:
names = df3["Name"]

In [253]:
names

852591               Hải Lê
190766    Đặng Thị Trúc Lam
473760          Thu Hien Le
62222        NgAng LÀ PhAng
562024             Ngọc Ánh
                ...
735107        Thúy's Đaoo's
988539          Đỗ Hà Trang
745337           Trang Phạm
231619               Mè Đại
983410        Fahad Mushtaq
Name: Name, Length: 1999998, dtype: object

In [254]:
names[0]

0    Nguyễn Đàm Quốc Huy
0     Nguyễn Thị Mỹ Linh
Name: Name, dtype: object

In [255]:
cv = CountVectorizer()
X = cv.fit_transform(names.values.astype('U'))

In [256]:
cv.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['23',
 'aa',
 'aabas',
 'aabb',
 'aabc',
 'aabdallah',
 'aabdltif',
 'aabed',
 'aabedelli',
 'aabha',
 'aabhay',
 'aabhishek',
 'aabid',
 'aacc',
 'aaccem',
 'aacu',
 'aad',
 'aadan',
 'aadarsh',
 'aadel',
 'aadesak',
 'aadesh',
 'aadhil',
 'aadhvik',
 'aadi',
 'aadii',
 'aadil',
 'aadim',
 'aadish',
 'aadito',
 'aaditya',
 'aae',
 'aafaque',
 'aafiya',
 'aaftab',
 'aag',
 'aage',
 'aagle',
 'aahil',
 'aahka',
 'aahmad',
 'aahmed',
 'aahna',
 'aahıl',
 'aai',
 'aaiza',
 'aaj',
 'aajad',
 'aak',
 'aakal',
 'aakash',
 'aakheb',
 'aakib',
 'aakriti',
 'aal',
 'aalam',
 'aalamtrader',
 'aalborg',
 'aali',
 'aalia',
 'aalif',
 'aalim',
 'aalinarrohman',
 'aalisha',
 'aaliya',
 'aaliyah',
 'aalpha',
 'aam',
 'aaman',
 'aamer',
 'aamhi',
 'aamin',
 'aamir',
 'aamirul',
 'aamis',
 'aamri',
 'aan',
 'aanand',
 'aanas',
 'aandtt',
 'aang',
 'aanh',
 'aanhthu',
 'aanika',
 'aanil',
 'aanjana',
 'aann',
 'aannao',
 'aanne',
 'aannhh',
 'aansari',
 'aap',
 'aaphak',
 'aapon',
 'aapte',
 'aapud',
 'aaq',
 'aaqib',
 'aaquib',
 'aar',
 'aaradha',
 'aarahizaa',
 'aaralete',
 'aaratee',
 'aarav',
 'aarbaj',
 'aarfa',
 'aaric',
 'aarif',
 'aariyan',
 'aariz',
 'aarjoo',
 'aarobi',
 'aarogya',
 'aarohi',
 'aaron',
 'aaronkm',
 'aaronsito',
 'aarthana',
 'aarti',
 'aarty',
 'aaru',
 'aarumugam',
 'aarush',
 'aarya',
 'aaryan',
 'aarzu',
 'aaróm',
 'aas',
 'aasad',
 'aashar',
 'aashe',
 'aashif',
 'aashik',
 'aashiq',
 'aashiqi',
 'aashish',
 'aashu',
 'aashutosh',
 'aasif',
 'aasik',
 'aasiko',
 'aasim',
 'aasish',
 'aasu',
 'aatesh',
 'aathwale',
 'aatif',
 'aatik',
 'aatir',
 'aatish',
 'aatrox',
 'aaty',
 'aau',
 'aaug',
 'aaves',
 'aavez',
 'aawati',
 'aawes',
 'aawez',
 'aay',
 'aayan',
 'aayman',
 'aayul',
 'aayush',
 'aayyad',
 'aazaan',
 'aazad',
 'aazam',
 'aazan',
 'aazib',
 'aazmin',
 'aazəef',
 'ab',
 'aba',
 'abaa',
 'abaalhusn',
 'abaas',
 'ababoor',
 'ababy',
 'abacha',
 'abad',
 'abada',
 'abaday',
 'abade',
 'abadi',
 'abadilla',
 'abadou',
 'abady',
 'abae',
 'abafita',
 'abager',
 'abah',
 'abaid',
 'abaidullah',
 'abais',
 'abaja',
 'abakai',
 'abakar',
 'abalorio',
 'abalos',
 'abalum',
 'abamba',
 'aban',
 'abana',
 'abang',
 'abank',
 'abankwa',
 'abanob',
 'abanoub',
 'abanto',
 'abao',
 'abaodoi',
 'abar',
 'abarabar',
 'abarah',
 'abarca',
 'abarna',
 'abaro',
 'abas',
 'abaseen',
 'abasi',
 'abaskuluoglu',
 'abass',
 'abastillas',
 'abat',
 'abatic',
 'abaton',
 'abatourabe',
 'abawi',
 'abaxial',
 'abay',
 'abayan',
 'abaykan',
 'abayomi',
 'abayon',
 'abba',
 'abbadi',
 'abbah',
 'abban',
 'abbang',
 'abbank',
 'abbar',
 'abbas',
 'abbasali',
 'abbasi',
 'abbasov',
 'abbasprince',
 'abbass',
 'abbate',
 'abbaxi',
 'abbes',
 'abbey',
 'abbi',
 'abbie',
 'abbos',
 'abbott',
 'abbotti',
 'abboud',
 'abbs',
 'abbu',
 'abbulah',
 'abby',
 'abbâs',
 'abbès',
 'abbé',
 'abc',
 'abcabc',
 'abcmhmgtg',
 'abcmobie',
 'abcmobile',
 'abcom',
 'abcstore',
 'abd',
 'abdaal',
 'abdal',
 'abdala',
 'abdalah',
 'abdalaleem',
 'abdalh',
 'abdalhade',
 'abdalhmeed',
 'abdali',
 'abdalla',
 'abdallah',
 'abdallahi',
 'abdallahtarji',
 'abdallatif',
 'abdallatifu',
 'abdallh',
 'abdalrheem',
 'abdalshaheed',
 'abdalwahd',
 'abdarahem',
 'abdarrhman',
 'abdataa',
 'abdbie',
 'abde',
 'abdeali',
 'abdee',
 'abdeel',
 'abdeen',
 'abdekader',
 'abdel',
 'abdela',
 'abdelaal',
 'abdelali',
 'abdelatif',
 'abdelazem',
 'abdelazez',
 'abdelazim',
 'abdelaziz',
 'abdelbasset',
 'abdelfatah',
 'abdelfateh',
 'abdelftah',
 'abdelghani',
 'abdelhady',
 'abdelhafez',
 'abdelhafid',
 'abdelhak',
 'abdelhakim',
 'abdelhamed',
 'abdelhameed',
 'abdelhamid',
 'abdelhamide',
 'abdelhlim',
 'abdelilah',
 'abdelillah',
 'abdeljelil',
 'abdelkader',
 'abdelkarim',
 'abdelkrim',
 'abdella',
 'abdellah',
 'abdellahi',
 'abdellaoui',
 'abdellatif',
 'abdelmadjide',
 'abdelmaqsod',
 'abdelmenim',
 'abdelmjid',
 'abdelmoaaty',
 'abdelmoez',
 'abdelmoize',
 'abdelmonem',
 'abdelmorit',
 'abdelnaby',
 'abdelouahab',
 'abdelr',
 'abdelrahman',
 'abdelrheem',
 'abdelrhman',
 'abdelsalam',
 'abdeltif',
 'abdelwafi',
 'abdelwahab',
 'abdelwahed',
 'abder',
 'abderahim',
 'abderahman',
 'abderazak',
 'abderezzak',
 'abderrahim',
 'abderrahman',
 'abderrahmane',
 'abderrazak',
 'abdes',
 'abdessalam',
 'abdessamad',
 'abdessamie',
 'abdessmad',
 'abdi',
 'abdiaziz',
 'abdiev',
 'abdifitaah',
 'abdifitah',
 'abdii',
 'abdikadir',
 'abdikafi',
 'abdikariim',
 'abdikariin',
 'abdillachi',
 'abdillah',
 'abdillahi',
 'abdimajid',
 'abdin',
 'abdinasir',
 'abdinazer',
 'abdinor',
 'abdinur',
 'abdinuur',
 'abdiono',
 'abdiqani',
 'abdirahmaan',
 'abdirahman',
 'abdirashiid',
 'abdiraxiim',
 'abdiredwan',
 'abdirisack',
 'abdisa',
 'abdisalam',
 'abdisalan',
 'abdishukur',
 'abdl',
 'abdlatif',
 'abdlghani',
 'abdlhadi',
 'abdlhak',
 'abdljalil',
 'abdlkader',
 'abdlkrim',
 'abdlla',
 'abdllah',
 'abdllkaderbanessa',
 'abdlmajid',
 'abdlmoghit',
 'abdltif',
 'abdnour',
 'abdo',
 'abdoabdo',
 'abdoelrahman',
 'abdol',
 'abdolah',
 'abdolbaes',
 'abdollah',
 'abdollatif',
 'abdominous',
 'abdon',
 'abdoo',
 'abdooll',
 'abdorahim',
 'abdosamod',
 'abdou',
 'abdoul',
 'abdoulay',
 'abdoulaye',
 'abdoulie',
 'abdoulrazak',
 'abdourahim',
 'abdraboo',
 'abdrahim',
 'abdramane',
 'abdrazzak',
 'abdsalam',
 'abdsamad',
 'abdu',
 'abdual',
 'abduall',
 'abduallah',
 'abduh',
 'abdul',
 'abdula',
 'abdulaahi',
 'abdulafi',
 'abdulah',
 'abdulahi',
 'abdulai',
 'abdulakeem',
 'abdulal',
 'abdulalim',
 'abdulati',
 'abdulaye',
 'abdulazeem',
 'abdulazeez',
 'abdulazim',
 'abdulaziz',
 'abdulfatau',
 'abdulgani',
 'abdulgany',
 'abdulghani',
 'abdulhadi',
 'abdulhafeez',
 'abdulhalim',
 'abdulhameed',
 'abdulhaq',
 'abdulhey',
 'abduli',
 'abdulia',
 'abdulik',
 'abdulkader',
 'abdulkadir',
 'abdulkareem',
 'abdulkarim',
 'abdulkerim',
 'abdulkhailq',
 'abdulkhalik',
 'abdulkhaliq',
 'abdull',
 'abdulla',
 'abdullaahad',
 'abdullah',
 'abdullahalmamun',
 'abdullahi',
 'abdullatif',
 'abdullatifromlikarim',
 'abdullh',
 'abdullha',
 'abdulloh',
 'abdullrahman',
 'abdulmalik',
 'abdulmenaf',
 'abdulmonem',
 'abdulmuqim',
 'abdulpari',
 'abdulqyuom',
 'abdulrab',
 'abdulraheem',
 'abdulrahim',
 'abdulrahman',
 'abdulraof',
 'abdulraouf',
 'abdulrauf',
 'abdulrazak',
 'abdulrazzak',
 'abdulrazzaq',
 'abdulrehman',
 'abdulrhamn',
 'abdulrhman',
 'abdulrqeb',
 'abdulselam',
 'abdulshakoor',
 'abdulwahab',
 'abdulwaheed',
 'abdulwajed',
 'abdulwajid',
 'abdulwasi',
 'abduly',
 'abdumalik',
 'abdur',
 'abdurahan',
 'abdurahman',
 'abduraimo',
 'abdurajak',
 'abdurajil',
 'abdurasheed',
 'abdure',
 'abdurrahaman',
 'abdurrahim',
 'abdurrahman',
 'abdurrezzak',
 'abdus',
 'abdusalan',
 'abduselam',
 'abdutajil',
 'abduvali',
 'abdy',
 'abdygany',
 'abdylai',
 'abdülrāzzaāq',
 'abe',
 'abebe',
 'abed',
 'abedalrahman',
 'abedi',
 'abedien',
 'abedin',
 'abedo',
 'abeer',
 'abeera',
 'abeesh',
 'abegail',
 'abegaille',
 'abejar',
 'abejo',
 'abekeh',
 'abel',
 'abelardo',
 'abele',
 'abelika',
 'abeljawed',
 'abelk',
 'abell',
 'abella',
 'abellanosa',
 'abellon',
 'abeloski',
 'aben',
 'abenales',
 'abendan',
 'abendanio',
 'abenes',
 'abenezer',
 'aber',
 'abera',
 'aberaldo',
 'aberam',
 'abercrombie',
 'aberde',
 'abessolo',
 'abet',
 'abeto',
 'abewardhana',
 'abex',
 'abey',
 'abglang',
 'abhagi',
 'abhang',
 'abhas',
 'abhay',
 'abheeshek',
 'abhf',
 'abhi',
 'abhidancer',
 'abhie',
 'abhijeet',
 'abhijit',
 'abhik',
 'abhilash',
 'abhilasha',
 'abhimanyu',
 'abhina',
 'abhinandan',
 'abhinandn',
 'abhinav',
 'abhinavshukla',
 'abhiraj',
 'abhiram',
 'abhisaek',
 'abhisek',
 'abhish',
 'abhishek',
 'abhjiit',
 'abhy',
 'abhîshek',
 'abi',
 'abian',
 'abib',
 'abibat',
 'abibatu',
 'abibozak',
 'abiche',
 'abid',
 'abidal',
 'abidam',
 'abidemi',
 'abidi',
 'abidin',
 'abie',
 'abiee',
 'abiez',
 'abig',
 'abigail',
 'abigaëlle',
 'abiguela',
 'abiha',
 'abii',
 'abiigail',
 'abike',
 'abil',
 'abila',
 'abilah',
 'abilez',
 'abilgos',
 'abilio',
 'abima',
 'abimanyu',
 'abin',
 'abinash',
 'abinashyadav',
 'abines',
 'abinh',
 'abinøør',
 'abiodiin',
 'abiodun',
 'abiol',
 'abiola',
 'abir',
 'abiral',
 'abis',
 'abisa',
 'abishek',
 'abishman',
 'abisoko',
 'abisola',
 'abiss',
 'abisu',
 'abitong',
 'abity',
 'abiy',
 'abiyan',
 'abiyu',
 'abiñon',
 'abjashi',
 'abk',
 'abkindia',
 'ablaye',
 'ablaza',
 'able',
 'ablet',
 'ablett',
 'ablo',
 'abm',
 'abma',
 'abmaber',
 'abmcctv',
 'abmonm',
 'abn',
 'abnadavia',
 'abndi',
 'abne',
 'abner',
 'abnet',
 'abnoudy',
 'abns',
 'abnu',
 'abo',
 'aboagye',
 'abobakr',
 'aboda',
 'abodan',
 'abode',
 'abody',
 'aboe',
 'aboelkhir',
 'aboesmael',
 'abofarha',
 'abohasan',
 'abohelmy',
 'abohh',
 'aboi',
 'aboj',
 'abojamous',
 'abokiel',
 'abolaji',
 'abolet',
 'abolnaja',
 'abolo',
 'abolqasim',
 'abom',
 'abomaysoon',
 'abon',
 'abonado',
 'abonashy',
 'abonita',
 'abonitalla',
 'aboo',
 'abooaoof',
 'aboobacker',
 'abood',
 'abook',
 'aborayan',
 'aboreda',
 'abort',
 'abosamra',
 'abose',
 'abosee',
 'aboslima',
 'abosm',
 'abotalib',
 'abotsi',
 'abou',
 'abouamra',
 'aboubacar',
 'aboubakar',
 'aboubakr',
 'aboucha',
 'aboud',
 'aboul',
 'aboutaltmimi',
 'aboutariq',
 'abouziry',
 'abowaled',
 'aboy',
 'abozed',
 'abozeed',
 'abqari',
 'abr',
 'abra',
 'abraham',
 'abrahamsson',
 'abrahan',
 'abrahem',
 'abrahim',
 'abram',
 'abramovich',
 'abrams',
 'abran',
 'abranet',
 'abrantes',
 'abrantie',
 'abrar',
 'abrarbutt',
 'abraão',
 'abraços',
 'abrea',
 'abregana',
 'abrego',
 'abregu',
 'abrej',
 'abrematia',
 'abreshe',
 'abreu',
 'abrhman',
 'abria',
 'abrie',
 'abrigo',
 'abril',
 'abrilliiyan',
 'abrio',
 'abrisam',
 'abrish',
 'abro',
 'abroad',
 'abroguena',
 'abrougui',
 'abs',
 'absa',
 'absd',
 'abshop',
 'abslubly',
 'abspa',
 'abstone',
 'abstore',
 'abstrakk',
 'abt',
 'abtahi',
 'abtalya',
 'abu',
 'abuadam',
 'abuamin',
 'abubacar',
 'abubakar',
 'abubakari',
 'abubakarie',
 'abubaker',
 'abubakr',
 'abubatu',
 'abubo',
 'abuchi',
 'abudabi',
 'abudo',
 'abudulahi',
 'abufares',
 'abugam',
 'abuhager',
 'abuhena',
 'abuhon',
 'abuhuraira',
 'abui',
 'abuimaye',
 'abujarar',
 'abukar',
 'abul',
 'abula',
 'abulhamid',
 'abulkalam',
 'abullah',
 'abuml',
 'abuothman',
 'aburas',
 'aburaya',
 'aburizal',
 'aburto',
 'abusaid',
 'abusama',
 'abusayed',
 'abutaher',
 'abutahet',
 'abutaleb',
 'abutalha',
 'abuu',
 'abuy',
 'abuyuan',
 'abuzar',
 'abuzettin',
 'abuồn',
 'abvp',
 'abwihi',
 'aby',
 'abyadh',
 'abyan',
 'abygail',
 'abân',
 'abê',
 'abên',
 'abël',
 'abình',
 'abô',
 'aböra',
 'abďullaĥ',
 'abđul',
 'abđüłłáh',
 'ac',
 'aca',
 'acabal',
 'acac',
 'acacia',
 'academyadmin',
 'acai',
 'acain',
 'acam',
 'acap',
 'acapulco',
 'acar',
 'acara',
 'acaraju',
 'acas',
 'acasandrei',
 'acase',
 'acatrinei',
 'acau',
 'acay',
 'acb',
 'acbrs',
 'acc',
 'accademy',
 'accept',
 'accesories',
 'accesorios',
 'accesory',
 'accesscontrol',
 'accessories',
 'accessoris',
 'accessorises',
 'accessorize',
 'accidentally',
 'acclombessi',
 'accma',
 'accoauntant',
 'accordion',
 'accounting',
 'acctk',
 'accura',
 'accurance',
 'acd',
 'ace',
 'acebron',
 'aceh',
 'aceng',
 'acep',
 'acer',
 'acero',
 'aces',
 'acesee',
 'acessories',
 'acetate',
 'acevedo',
 'acg',
 'ach',
 'acha',
 'achado',
 'achai',
 'achakzai',
 'achan',
 'achang',
 'achanta',
 'achaq',
 'achar',
 'achari',
 'acharjee',
 'acharki',
 'acharya',
 'achau',
 'achav',
 'achay',
 'achazia',
 'achdi',
 'acheikh',
 'achel',
 'achen',
 'achi',
 'achieve',
 'achieved',
 'achievers',
 'achieveton',
 'achik',
 'achil',
 'achiles',
 'achilles',
 'achit',
 'achita',
 'achitecture',
 'achiteru',
 'achlaram',
 'achmad',
 'achmadz',
 'achour',
 'achraf',
 'achref',
 'achshavu',
 'achu',
 'achuan',
 'achui',
 'achury',
 'achuumi',
 'achy',
 'achâu',
 'achính',
 'achíu',
 'achề',
 'achỉ',
 'achức',
 'aci',
 'acibar',
 'acibo',
 'acid',
 'acidemir',
 'acido',
 'acierda',
 ...]

In [257]:
X
y = df3.Gender

In [258]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state=0)

In [259]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train,y_train)

MultinomialNB()

In [260]:
model.score(X_test,y_test)
print("Độ chính xác của mô hình",model.score(X_test, y_test)*100,"%")

Độ chính xác của mô hình 83.34448334448335 %

In [261]:
sample_name = ["Nguyễn Đàm Quốc Huy"]
vector = cv.transform(sample_name).toarray()

In [262]:
vector

array([[0, 0, 0, ..., 0, 0, 0]])

In [263]:
# Nam là 1, Nữ là 0
model.predict(vector)

array([1])

In [264]:
sample_name1 =["Nguyễn Thị Mỹ Linh"]
vector1 = cv.transform(sample_name1).toarray()
model.predict(vector1)

array([0])

In [265]:
sample_name2 =["Toàn Văn Cao"]
vector2 = cv.transform(sample_name2).toarray()
model.predict(vector2)

array([1])